// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAoAq65JEl9R4H-tGsVrYq_YgGcjkuZPM',
    appId: '1:173145337411:web:90f6b02efe0425bc15eef6',
    messagingSenderId: '173145337411',
    projectId: 'leaves-c2bec',
    authDomain: 'leaves-c2bec.firebaseapp.com',
    storageBucket: 'leaves-c2bec.firebasestorage.app',
    measurementId: 'G-34LQY2C5FN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXeYZ-nfyw-l6qxkmVebbskSUsizpHRbY',
    appId: '1:173145337411:android:6926841e03c77b5015eef6',
    messagingSenderId: '173145337411',
    projectId: 'leaves-c2bec',
    storageBucket: 'leaves-c2bec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQtO3lYmetvgQhnnFyJQMDd4T_W7Zek-k',
    appId: '1:173145337411:ios:722ee013735f042c15eef6',
    messagingSenderId: '173145337411',
    projectId: 'leaves-c2bec',
    storageBucket: 'leaves-c2bec.firebasestorage.app',
    iosBundleId: 'com.example.leaveManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQtO3lYmetvgQhnnFyJQMDd4T_W7Zek-k',
    appId: '1:173145337411:ios:722ee013735f042c15eef6',
    messagingSenderId: '173145337411',
    projectId: 'leaves-c2bec',
    storageBucket: 'leaves-c2bec.firebasestorage.app',
    iosBundleId: 'com.example.leaveManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAoAq65JEl9R4H-tGsVrYq_YgGcjkuZPM',
    appId: '1:173145337411:web:75100cde4544909c15eef6',
    messagingSenderId: '173145337411',
    projectId: 'leaves-c2bec',
    authDomain: 'leaves-c2bec.firebaseapp.com',
    storageBucket: 'leaves-c2bec.firebasestorage.app',
    measurementId: 'G-KKE7Z7GHG9',
  );

}